---
# tasks file for dhcpd

- name: Update repositories on hosts
  apt:
    update_cache: yes

- name: install isc-dhcp-server
  package:
    name: "isc-dhcp-server"
    state: latest

- name: install radvd
  package:
    name: "radvd"
    state: latest

- name: change /etc/default/isc-dhcp-server IPV4
  lineinfile:
    path: /etc/default/isc-dhcp-server
    state: present
    regexp: '^INTERFACESv4=\s'
    line: 'INTERFACESv4="br-ffintern"'

- name: change /etc/default/isc-dhcp-server IPV6
  lineinfile:
    path: /etc/default/isc-dhcp-server
    state: present
    regexp: '^INTERFACESv6=\s'
    line: 'INTERFACESv6="br-ffintern"'

- name: configure /etc/dhcpd.conf
  template:
    src: "dhcpd.conf.j2"
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644

- name: configure /etc/dhcpd6.conf
  template:
    src: "dhcpd6.conf.j2"
    dest: /etc/dhcp/dhcpd6.conf
    owner: root
    group: root
    mode: 0644

- name: configure /etc/radvd.conf
  template:
    src: "radvd.conf.j2"
    dest: /etc/radvd.conf
    owner: root
    group: root
    mode: 0644

- name: enable radvd and ensure it is not masked
  systemd:
    name: radvd
    enabled: yes
    masked: no

