---
# tasks file for fastd role
- name: install fastd
  apt:
    name: fastd
    state: latest
    update_cache: yes

- name: copy fastd files
  copy:
    src: "etc/fastd/"
    dest: "/etc/fastd"
    owner: root
    group: root
    mode: 0644

- name: configure fastd-vpn/fastd.conf
  template:
    src: "fastd-vpn.fastd.conf.j2"
    dest: /etc/fastd/fastd-vpn/fastd.conf
    owner: root
    group: root
    mode: 0644

- name: extend /etc/default/fastd
  lineinfile:
    path: /etc/default/fastd
    state: present
    regexp: '^AUTOSTART="none"\s'
    line: 'AUTOSTART="all"'

- name: change executable byte for files
  file:
    path: '/etc/fastd/{{ item }}'
    owner: root
    group: root
    mode: 0744
  with_items:
    - 'fastd-vpn/on-up'
    - 'fastd-blacklist.sh'
