---
# tasks file for bind
- name: install PDNS Recursor
  apt:
    name: "pdns-recursor"
    state: latest
    update_cache: yes

- name: copy /etc/powerdns/filter-aaaa.lua
  copy:
    src: "etc/powerdns/filter-aaaa.lua"
    dest: "/etc/powerdns/filter-aaaa.lua"
    owner: root
    group: root
    mode: 0644

- name: configure /etc/powerdns/recursor.conf
  template:
    src: "recursor.conf.j2"
    dest: /etc/powerdns/recursor.conf
    owner: root
    group: root
    mode: 0644

