#!/bin/sh

/sbin/ip link set dev fastd-vpn up

batctl if add fastd-vpn
batctl it 5000
batctl gw_mode server 300MBit/300MBit
batctl hp 60                    #Change hop_penalty
batctl bl 1			#Bridge loop detection aktivieren

/sbin/ip rule show | grep 'from 10.70.0.0/16 lookup freifunk'
if [ $? -eq 1 ]; then
  /sbin/ip rule add from 10.70.0.0/16 table freifunk
fi
/sbin/ip route add 10.70.0.0/16 dev br-ffintern table freifunk
/sbin/ip route flush cache
 
/sbin/ip route flush cache
